modLoader = "javafml"
loaderVersion = "[46,)"
license = "CC BY-NC-SA 4.0"

[[mods]]
modId = "touhou_little_maid"
version = "${file.jarVersion}"
displayName = "Touhou Little Maid"
issueTrackerURL = "https://github.com/TartaricAcid/TouhouLittleMaid/issues"
displayURL = "https://discord.gg/re4xQtb"
logoFile = "logo.png"
credits = "Verclene, ZUN"
# A text field displayed in the mod UI
authors = "TartaricAcid, Snownee, Succinum, Pajinyi, CrystalizedSun, ZeniCrow, Paulzzh, Yuriscat, Lappland162"
# The description text for the mod (multi line!) (#mandatory)
description = "A new version of the minecraft mod inspired by the LittleMaidReengaged mod."

[modproperties.touhou_little_maid]
catalogueItemIcon = "touhou_little_maid:hakurei_gohei"

[[dependencies.touhou_little_maid]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.touhou_little_maid]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.20.2)"
ordering = "NONE"
side = "BOTH"