modLoader = "javafml"
loaderVersion = "[36,)"
license = "CC-BY-NC-SA"

[[mods]]
modId = "touhou_little_maid"
version = "${file.jarVersion}"
displayName = "Touhou Little Maid"
# logoFile="examplemod.png"
credits = "Verclene, ZUN"
# A text field displayed in the mod UI
authors = "TartaricAcid, Snownee, Succinum, Pajinyi, ZeniCrow, Paulzzh, Yuriscat, Lappland162"
# The description text for the mod (multi line!) (#mandatory)
description = '''
    A new version of the minecraft mod inspired by the LittleMaidReengaged mod.
    '''